services:
  - type: web
    name: fraud-db-dashboard
    env: python            
    plan: free            

 
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

 
    startCommand: |
      python fraud_alert_dashboard.py --port $PORT


    autoDeploy: true